-- 1. patients (with login & verification)
CREATE TABLE patients (
    patient_id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    gender CHAR(1) CHECK (gender IN ('M', 'F', 'O')),
    date_of_birth DATE NOT NULL,
    contact_number VARCHAR(15),
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,  -- hashed password
    address TEXT,
    is_active BOOLEAN DEFAULT FALSE, -- becomes TRUE after verification
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. users (staff accounts: admin, doctors, technicians)
CREATE TABLE users (
    user_id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    role VARCHAR(20) CHECK (role IN ('admin', 'lab_tech', 'doctor')),
    password VARCHAR(255) NOT NULL,
    is_active BOOLEAN DEFAULT FALSE, -- verified staff
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3. tests (global catalog for the single lab)
CREATE TABLE tests (
    test_id SERIAL PRIMARY KEY,
    test_name VARCHAR(100) NOT NULL,
    description TEXT,
    sample_type VARCHAR(50) CHECK (sample_type IN ('blood', 'urine', 'saliva', 'tissue', 'other')),
    price DECIMAL(10,2) NOT NULL
);

-- 4. test_parameters (belong to tests)
CREATE TABLE test_parameters (
    parameter_id SERIAL PRIMARY KEY,
    test_id INT REFERENCES tests(test_id) ON DELETE CASCADE,
    name VARCHAR(100) NOT NULL,
    unit VARCHAR(50),
    ref_range_male VARCHAR(100),
    ref_range_female VARCHAR(100),
    ref_range_child VARCHAR(100)
);

-- 5. bookings (patient test bookings)
CREATE TABLE bookings (
    booking_id SERIAL PRIMARY KEY,
    patient_id INT REFERENCES patients(patient_id) ON DELETE CASCADE,
    user_id INT REFERENCES users(user_id), -- staff who created booking
    booking_date DATE NOT NULL,
    status VARCHAR(20) CHECK (status IN ('pending', 'completed', 'cancelled')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 6. booking_tests (link between bookings & tests)
CREATE TABLE booking_tests (
    id SERIAL PRIMARY KEY,
    booking_id INT REFERENCES bookings(booking_id) ON DELETE CASCADE,
    test_id INT REFERENCES tests(test_id) ON DELETE CASCADE,
    interpretation TEXT DEFAULT 'NA',
    UNIQUE (booking_id, test_id)
);

-- 7. samples (collected for tests)
CREATE TABLE samples (
    sample_id SERIAL PRIMARY KEY,
    booking_id INT REFERENCES bookings(booking_id) ON DELETE CASCADE,
    test_id INT REFERENCES tests(test_id) ON DELETE CASCADE,
    collected_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    collected_by INT REFERENCES users(user_id),
    status VARCHAR(20) CHECK (status IN ('collection_pending', 'collected', 'in_transit', 'received', 'tested', 'discarded')),
    notes TEXT
);

-- 8. test_results (parameter-level results)
CREATE TABLE test_results (
    result_id SERIAL PRIMARY KEY,
    booking_id INT REFERENCES bookings(booking_id) ON DELETE CASCADE,
    parameter_id INT REFERENCES test_parameters(parameter_id) ON DELETE CASCADE,
    value VARCHAR(100),
    user_id INT REFERENCES users(user_id), -- who entered result
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 9. reports (generated PDF/Cloud URLs)
CREATE TABLE reports (
    report_id SERIAL PRIMARY KEY,
    booking_id INT UNIQUE REFERENCES bookings(booking_id) ON DELETE CASCADE,
    user_id INT REFERENCES users(user_id), -- generated by
    report_file VARCHAR(255) NOT NULL,
    generated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 10. payments (per booking)
CREATE TABLE payments (
    payment_id SERIAL PRIMARY KEY,
    booking_id INT REFERENCES bookings(booking_id) ON DELETE CASCADE,
    amount DECIMAL(10,2) NOT NULL,
    status VARCHAR(20) CHECK (status IN ('paid', 'pending')),
    paid_at TIMESTAMP
);

-- 11. logs (activity audit, scoped to users/patients)
CREATE TABLE logs (
    log_id SERIAL PRIMARY KEY,
    user_id INT REFERENCES users(user_id),
    patient_id INT REFERENCES patients(patient_id),
    action TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 12. prescriptions (doctor uploaded)
CREATE TABLE prescriptions (
    prescription_id SERIAL PRIMARY KEY,
    patient_id INT REFERENCES patients(patient_id) ON DELETE CASCADE,
    booking_id INT REFERENCES bookings(booking_id) ON DELETE SET NULL,
    doctor_name VARCHAR(150) NOT NULL,
    prescription_url VARCHAR(255) NOT NULL,  -- Cloud storage URL
    notes TEXT,
    uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 13. password history (for both patients & users)
CREATE TABLE password_history (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    user_type VARCHAR(20) CHECK (user_type IN ('patient','user')),
    ref_id BIGINT NOT NULL, -- patient_id or user_id
    password VARCHAR(255) NOT NULL,
    change_date TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL
);

-- 14. password reset tokens
CREATE TABLE password_reset_tokens (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    token VARCHAR(255) NOT NULL UNIQUE,
    user_type VARCHAR(20) CHECK (user_type IN ('patient','user')),
    ref_id BIGINT NOT NULL,
    expiry_date TIMESTAMP NOT NULL
);

-- 15. email verification tokens
CREATE TABLE email_verification_tokens (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    token VARCHAR(255) NOT NULL UNIQUE,
    user_type VARCHAR(20) CHECK (user_type IN ('patient','user')),
    ref_id BIGINT NOT NULL,
    expiry_date TIMESTAMP NOT NULL
);
-- Create table for JWT blacklist to support logout token invalidation
CREATE TABLE IF NOT EXISTS blacklisted_jwts (
    id BIGSERIAL PRIMARY KEY,
    token TEXT NOT NULL,
    expiry_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Optional index for faster lookups by token
CREATE INDEX IF NOT EXISTS idx_blacklisted_jwts_token ON blacklisted_jwts(token);



-- Indexes for performance
CREATE INDEX idx_booking_tests ON booking_tests(booking_id, test_id);
CREATE INDEX idx_samples_booking ON samples(booking_id);
CREATE INDEX idx_results_booking ON test_results(booking_id);
CREATE INDEX idx_patients_email ON patients(email);
CREATE INDEX idx_users_email ON users(email);
